-- Create Database
CREATE DATABASE IF NOT EXISTS professional_network;
USE professional_network;

-- Users Table
CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    F_NAME VARCHAR(100) NOT NULL,
    L_NAME VARCHAR(100) NOT NULL,
    DOB DATE,
    INDUSTRY VARCHAR(100),
    PROFILE_PIC_URL VARCHAR(500),
    COUNTRY VARCHAR(100),
    CITY VARCHAR(100),
    BIO TEXT,
    HEADLINE VARCHAR(255),
    STATUS ENUM('active', 'inactive', 'suspended') DEFAULT 'active',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_email (EMAIL),
    INDEX idx_status (STATUS)
);

-- Connections Table
CREATE TABLE CONNECTIONS (
    CONNECTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    REQUEST_ID INT NOT NULL,
    RECEIVER_ID INT NOT NULL,
    STATUS ENUM('pending', 'accepted', 'rejected') DEFAULT 'pending',
    REQUESTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACCEPTED_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (REQUEST_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX idx_status (STATUS),
    INDEX idx_receiver (RECEIVER_ID)
);

-- Experience Table
CREATE TABLE EXPERIENCE (
    EXPERIENCE_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    JOB_TITLE VARCHAR(150) NOT NULL,
    EMPLOYMENT_TYPE ENUM('Full-time', 'Part-time', 'Contract', 'Internship', 'Freelance'),
    LOCATION VARCHAR(200),
    JOB_DESCRIPTION TEXT,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX idx_user (USER_ID),
    INDEX idx_current (IS_CURRENT)
);

-- Education Table
CREATE TABLE EDUCATION (
    EDUCATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    INSTITUTION_NAME VARCHAR(200) NOT NULL,
    FIELD_OF_STUDY VARCHAR(150),
    DEGREE VARCHAR(100),
    DESCRIPTION TEXT,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX idx_user (USER_ID)
);

-- Skills Table
CREATE TABLE SKILLS (
    SKILL_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    SKILL VARCHAR(100) NOT NULL,
    PROFICIENCY_LVL ENUM('Beginner', 'Intermediate', 'Advanced', 'Expert'),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX idx_user (USER_ID),
    INDEX idx_skill (SKILL)
);

-- Posts Table
CREATE TABLE POSTS (
    POST_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    TITLE VARCHAR(255),
    CONTENT TEXT NOT NULL,
    MEDIA_URL VARCHAR(500),
    POST_TYPE ENUM('text', 'image', 'video', 'article') DEFAULT 'text',
    LIKES_COUNT INT DEFAULT 0,
    COMMENTS_COUNT INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX idx_user (USER_ID),
    INDEX idx_created (CREATED_AT)
);

-- Post Likes Table
CREATE TABLE POST_LIKES (
    LIKE_ID INT AUTO_INCREMENT PRIMARY KEY,
    POST_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    UNIQUE KEY unique_post_like (POST_ID, USER_ID),
    INDEX idx_post (POST_ID),
    INDEX idx_user (USER_ID)
);

-- Comments Table
CREATE TABLE COMMENTS (
    COMMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    POST_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CONTENT TEXT NOT NULL,
    LIKES_COUNT INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX idx_post (POST_ID),
    INDEX idx_user (USER_ID)
);

-- Comment Likes Table
CREATE TABLE COMMENT_LIKES (
    LIKE_ID INT AUTO_INCREMENT PRIMARY KEY,
    COMMENT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (COMMENT_ID) REFERENCES COMMENTS(COMMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    UNIQUE KEY unique_comment_like (COMMENT_ID, USER_ID),
    INDEX idx_comment (COMMENT_ID),
    INDEX idx_user (USER_ID)
);

-- NEW: Projects Table
CREATE TABLE PROJECTS (
    PROJECT_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    PROJECT_TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    TECHNOLOGIES_USED VARCHAR(500),
    PROJECT_URL VARCHAR(500),
    GITHUB_URL VARCHAR(500),
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    IS_ONGOING BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX idx_user (USER_ID),
    INDEX idx_ongoing (IS_ONGOING)
);

-- NEW: Resume Templates Table
CREATE TABLE RESUME_TEMPLATES (
    TEMPLATE_ID INT AUTO_INCREMENT PRIMARY KEY,
    TEMPLATE_NAME VARCHAR(100) NOT NULL,
    TEMPLATE_TYPE ENUM('Classic', 'Modern', 'Minimal', 'Creative') DEFAULT 'Classic',
    HTML_STRUCTURE TEXT,
    CSS_STYLING TEXT,
    PREVIEW_IMAGE_URL VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_type (TEMPLATE_TYPE)
);

-- NEW: User Resume Settings Table
CREATE TABLE USER_RESUME_SETTINGS (
    SETTINGS_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    TEMPLATE_ID INT NOT NULL,
    INCLUDE_PROFILE_PIC BOOLEAN DEFAULT TRUE,
    INCLUDE_BIO BOOLEAN DEFAULT TRUE,
    INCLUDE_PROJECTS BOOLEAN DEFAULT TRUE,
    SECTIONS_ORDER JSON,
    COLOR_SCHEME VARCHAR(50) DEFAULT '#000000',
    FONT_STYLE VARCHAR(50) DEFAULT 'Arial',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (TEMPLATE_ID) REFERENCES RESUME_TEMPLATES(TEMPLATE_ID),
    UNIQUE KEY unique_user_settings (USER_ID),
    INDEX idx_user (USER_ID)
);

-- NEW: Project Collaborators Table (Optional - for team projects)
CREATE TABLE PROJECT_COLLABORATORS (
    COLLABORATOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    PROJECT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    ROLE VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    UNIQUE KEY unique_project_collaborator (PROJECT_ID, USER_ID),
    INDEX idx_project (PROJECT_ID),
    INDEX idx_user (USER_ID)
);

-- NEW: User Activity Table (Track all user activities)
CREATE TABLE USER_ACTIVITY (
    ACTIVITY_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    ACTIVITY_TYPE ENUM('post', 'comment', 'like_post', 'like_comment', 'connection') NOT NULL,
    REFERENCE_ID INT NOT NULL,
    ACTIVITY_TEXT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    INDEX idx_user (USER_ID),
    INDEX idx_type (ACTIVITY_TYPE),
    INDEX idx_created (CREATED_AT)
);

-- ============================================
-- TRIGGERS FOR AUTOMATIC COUNT UPDATES
-- ============================================

-- Trigger: Increment post likes count when a like is added
DELIMITER //
CREATE TRIGGER after_post_like_insert
AFTER INSERT ON POST_LIKES
FOR EACH ROW
BEGIN
    UPDATE POSTS 
    SET LIKES_COUNT = LIKES_COUNT + 1 
    WHERE POST_ID = NEW.POST_ID;
    
    -- Log activity
    INSERT INTO USER_ACTIVITY (USER_ID, ACTIVITY_TYPE, REFERENCE_ID, ACTIVITY_TEXT)
    VALUES (NEW.USER_ID, 'like_post', NEW.POST_ID, 'Liked a post');
END//
DELIMITER ;

-- Trigger: Decrement post likes count when a like is removed
DELIMITER //
CREATE TRIGGER after_post_like_delete
AFTER DELETE ON POST_LIKES
FOR EACH ROW
BEGIN
    UPDATE POSTS 
    SET LIKES_COUNT = GREATEST(LIKES_COUNT - 1, 0)
    WHERE POST_ID = OLD.POST_ID;
END//
DELIMITER ;

-- Trigger: Increment comment count when a comment is added
DELIMITER //
CREATE TRIGGER after_comment_insert
AFTER INSERT ON COMMENTS
FOR EACH ROW
BEGIN
    UPDATE POSTS 
    SET COMMENTS_COUNT = COMMENTS_COUNT + 1 
    WHERE POST_ID = NEW.POST_ID;
    
    -- Log activity
    INSERT INTO USER_ACTIVITY (USER_ID, ACTIVITY_TYPE, REFERENCE_ID, ACTIVITY_TEXT)
    VALUES (NEW.USER_ID, 'comment', NEW.COMMENT_ID, SUBSTRING(NEW.CONTENT, 1, 100));
END//
DELIMITER ;

-- Trigger: Decrement comment count when a comment is deleted
DELIMITER //
CREATE TRIGGER after_comment_delete
AFTER DELETE ON COMMENTS
FOR EACH ROW
BEGIN
    UPDATE POSTS 
    SET COMMENTS_COUNT = GREATEST(COMMENTS_COUNT - 1, 0)
    WHERE POST_ID = OLD.POST_ID;
END//
DELIMITER ;

-- Trigger: Increment comment likes count when a like is added
DELIMITER //
CREATE TRIGGER after_comment_like_insert
AFTER INSERT ON COMMENT_LIKES
FOR EACH ROW
BEGIN
    UPDATE COMMENTS 
    SET LIKES_COUNT = LIKES_COUNT + 1 
    WHERE COMMENT_ID = NEW.COMMENT_ID;
    
    -- Log activity
    INSERT INTO USER_ACTIVITY (USER_ID, ACTIVITY_TYPE, REFERENCE_ID, ACTIVITY_TEXT)
    VALUES (NEW.USER_ID, 'like_comment', NEW.COMMENT_ID, 'Liked a comment');
END//
DELIMITER ;

-- Trigger: Decrement comment likes count when a like is removed
DELIMITER //
CREATE TRIGGER after_comment_like_delete
AFTER DELETE ON COMMENT_LIKES
FOR EACH ROW
BEGIN
    UPDATE COMMENTS 
    SET LIKES_COUNT = GREATEST(LIKES_COUNT - 1, 0)
    WHERE COMMENT_ID = OLD.COMMENT_ID;
END//
DELIMITER ;

-- Trigger: Log post creation activity
DELIMITER //
CREATE TRIGGER after_post_insert
AFTER INSERT ON POSTS
FOR EACH ROW
BEGIN
    INSERT INTO USER_ACTIVITY (USER_ID, ACTIVITY_TYPE, REFERENCE_ID, ACTIVITY_TEXT)
    VALUES (NEW.USER_ID, 'post', NEW.POST_ID, COALESCE(NEW.TITLE, SUBSTRING(NEW.CONTENT, 1, 100)));
END//
DELIMITER ;

-- Trigger: Log connection acceptance activity
DELIMITER //
CREATE TRIGGER after_connection_accepted
AFTER UPDATE ON CONNECTIONS
FOR EACH ROW
BEGIN
    IF NEW.STATUS = 'accepted' AND OLD.STATUS = 'pending' THEN
        -- Log activity for both users
        INSERT INTO USER_ACTIVITY (USER_ID, ACTIVITY_TYPE, REFERENCE_ID, ACTIVITY_TEXT)
        VALUES (NEW.REQUEST_ID, 'connection', NEW.CONNECTION_ID, 'Connected with a user');
        
        INSERT INTO USER_ACTIVITY (USER_ID, ACTIVITY_TYPE, REFERENCE_ID, ACTIVITY_TEXT)
        VALUES (NEW.RECEIVER_ID, 'connection', NEW.CONNECTION_ID, 'Connected with a user');
    END IF;
END//
DELIMITER ;

-- ============================================
-- STORED PROCEDURES
-- ============================================

-- Procedure: Get user feed (posts from connections only)
DELIMITER //
CREATE PROCEDURE GetUserFeed(IN p_user_id INT, IN p_limit INT, IN p_offset INT)
BEGIN
    SELECT p.*, u.F_NAME, u.L_NAME, u.PROFILE_PIC_URL, u.HEADLINE,
           p.CREATED_AT as createdAt,
           EXISTS(
               SELECT 1 FROM POST_LIKES pl 
               WHERE pl.POST_ID = p.POST_ID AND pl.USER_ID = p_user_id
           ) as isLiked
    FROM POSTS p
    JOIN USERS u ON p.USER_ID = u.USER_ID
    WHERE u.STATUS = 'active'
    AND p.USER_ID != p_user_id
    AND (
        p.USER_ID IN (
            SELECT CASE 
                WHEN REQUEST_ID = p_user_id THEN RECEIVER_ID
                WHEN RECEIVER_ID = p_user_id THEN REQUEST_ID
            END as connected_user_id
            FROM CONNECTIONS
            WHERE (REQUEST_ID = p_user_id OR RECEIVER_ID = p_user_id)
            AND STATUS = 'accepted'
        )
        OR p.USER_ID = p_user_id
    )
    ORDER BY p.CREATED_AT DESC
    LIMIT p_limit OFFSET p_offset;
END//
DELIMITER ;

-- Procedure: Get user activity history
DELIMITER //
CREATE PROCEDURE GetUserActivity(IN p_user_id INT, IN p_limit INT)
BEGIN
    SELECT 
        ua.ACTIVITY_ID,
        ua.ACTIVITY_TYPE,
        ua.ACTIVITY_TEXT,
        ua.CREATED_AT,
        CASE ua.ACTIVITY_TYPE
            WHEN 'post' THEN (SELECT TITLE FROM POSTS WHERE POST_ID = ua.REFERENCE_ID)
            WHEN 'comment' THEN (SELECT CONTENT FROM COMMENTS WHERE COMMENT_ID = ua.REFERENCE_ID)
            ELSE NULL
        END as reference_title,
        CASE ua.ACTIVITY_TYPE
            WHEN 'post' THEN (SELECT POST_ID FROM POSTS WHERE POST_ID = ua.REFERENCE_ID)
            WHEN 'comment' THEN (SELECT POST_ID FROM COMMENTS WHERE COMMENT_ID = ua.REFERENCE_ID)
            WHEN 'like_post' THEN ua.REFERENCE_ID
            WHEN 'like_comment' THEN (SELECT POST_ID FROM COMMENTS WHERE COMMENT_ID = ua.REFERENCE_ID)
            ELSE NULL
        END as post_id
    FROM USER_ACTIVITY ua
    WHERE ua.USER_ID = p_user_id
    ORDER BY ua.CREATED_AT DESC
    LIMIT p_limit;
END//
DELIMITER ;

-- Procedure: Get mutual connections count
DELIMITER //
CREATE PROCEDURE GetMutualConnectionsCount(IN p_user_id1 INT, IN p_user_id2 INT)
BEGIN
    SELECT COUNT(*) as mutual_count
    FROM (
        SELECT CASE 
            WHEN REQUEST_ID = p_user_id1 THEN RECEIVER_ID
            WHEN RECEIVER_ID = p_user_id1 THEN REQUEST_ID
        END as connection_id
        FROM CONNECTIONS
        WHERE (REQUEST_ID = p_user_id1 OR RECEIVER_ID = p_user_id1)
        AND STATUS = 'accepted'
    ) as user1_connections
    INNER JOIN (
        SELECT CASE 
            WHEN REQUEST_ID = p_user_id2 THEN RECEIVER_ID
            WHEN RECEIVER_ID = p_user_id2 THEN REQUEST_ID
        END as connection_id
        FROM CONNECTIONS
        WHERE (REQUEST_ID = p_user_id2 OR RECEIVER_ID = p_user_id2)
        AND STATUS = 'accepted'
    ) as user2_connections
    ON user1_connections.connection_id = user2_connections.connection_id;
END//
DELIMITER ;

-- Procedure: Get connection suggestions (2nd degree connections)
DELIMITER //
CREATE PROCEDURE GetConnectionSuggestions(IN p_user_id INT, IN p_limit INT)
BEGIN
    SELECT DISTINCT u.USER_ID, u.F_NAME, u.L_NAME, u.HEADLINE, 
           u.PROFILE_PIC_URL, u.CITY, u.COUNTRY,
           COUNT(DISTINCT c2.CONNECTION_ID) as mutual_connections
    FROM USERS u
    JOIN CONNECTIONS c2 ON (c2.REQUEST_ID = u.USER_ID OR c2.RECEIVER_ID = u.USER_ID)
    WHERE u.USER_ID != p_user_id
    AND u.STATUS = 'active'
    AND u.USER_ID NOT IN (
        SELECT CASE 
            WHEN REQUEST_ID = p_user_id THEN RECEIVER_ID
            WHEN RECEIVER_ID = p_user_id THEN REQUEST_ID
        END
        FROM CONNECTIONS
        WHERE (REQUEST_ID = p_user_id OR RECEIVER_ID = p_user_id)
    )
    AND (c2.REQUEST_ID IN (
        SELECT CASE 
            WHEN REQUEST_ID = p_user_id THEN RECEIVER_ID
            WHEN RECEIVER_ID = p_user_id THEN REQUEST_ID
        END
        FROM CONNECTIONS
        WHERE (REQUEST_ID = p_user_id OR RECEIVER_ID = p_user_id)
        AND STATUS = 'accepted'
    ) OR c2.RECEIVER_ID IN (
        SELECT CASE 
            WHEN REQUEST_ID = p_user_id THEN RECEIVER_ID
            WHEN RECEIVER_ID = p_user_id THEN REQUEST_ID
        END
        FROM CONNECTIONS
        WHERE (REQUEST_ID = p_user_id OR RECEIVER_ID = p_user_id)
        AND STATUS = 'accepted'
    ))
    GROUP BY u.USER_ID
    ORDER BY mutual_connections DESC
    LIMIT p_limit;
END//
DELIMITER ;
